# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iosSand' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  

  # Pods for sandy
  pod 'Firebase', '>=2.5.0'
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'FirebaseUI/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Core'

end

